# Generated by Django 6.0.1 on 2026-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload an image for the front page', upload_to='frontpage/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image on front page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Front Page Image',
                'verbose_name_plural': 'Front Page Images',
            },
        ),
    ]
